### ISSUE TITLE
About the program:main_training_3GCN

### ISSUE THREAD

**Issue by kkwd22** [erinqhu/EEG-motor-imagery#1]
def train():
    model.train()
    running_loss = 0
    accuracy = 0
    for batch in trainloader:
        # Use GPU
        batch.cuda() 
        # Reset gradients
        optimizer.zero_grad()
        # Passing the node features and the connection info
        pred = model(batch.x.float(), batch.edge_index, batch.batch, batch.edge_attr.flatten()) 
        # Calculating the loss and gradients
        loss = criterion(pred, batch.y)
        loss.backward()
        running_loss += loss.item()
        # Update using the gradients
        optimizer.step()
        accuracy += (torch.argmax(pred, dim=1) == batch.y).float().mean()
    return running_loss/len(trainloader), accuracy/len(trainloader)
The for batch in trainloader: will report an error, the trainloader cannot be traversed

**Comment by kkwd22** [comment]
cannot pickle 'generator' object

**Comment by kkwd22** [comment]
Traceback (most recent call last):
  File "E:\Nao\EEG-motor-imagery-main\src\main.py", line 230, in <module>
    train_loss, train_acc = train(trainloader)
  File "E:\Nao\EEG-motor-imagery-main\src\main.py", line 109, in train
    for batch in trainloader:
  File "D:\Python\Anaconda\envs\gcn\lib\site-packages\torch\utils\data\dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "D:\Python\Anaconda\envs\gcn\lib\site-packages\torch\utils\data\dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "D:\Python\Anaconda\envs\gcn\lib\site-packages\torch\utils\data\dataloader.py", line 918, in __init__
    w.start()
  File "D:\Python\Anaconda\envs\gcn\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "D:\Python\Anaconda\envs\gcn\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Python\Anaconda\envs\gcn\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "D:\Python\Anaconda\envs\gcn\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Python\Anaconda\envs\gcn\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'generator' object

Process finished with exit code 1

**Comment by kkwd22** [comment]
can you help me,thanks
